Draft: Chat functions with live syncing
Bawnorton/Bamboozlers pull request #140
Opened 2024-04-06 21:04 UTC by Bawnorton

## Scope:
- [x] Message Editing
- [x] Message Pinning
- [ ] Message Replying
- [ ] Mentioning

All features with live syncing so for example if client A is looking at message B in the pins view and client C edits message B, client A will see message B in the pins update live.

2024-04-09 03:24 UTC, bhunt02 requested changes
gave everything a thorough test as part of my work in #143, noticing some issues. i think this might be another instance of blazor being lazy with parameters

2024-04-09 03:24 UTC, bhunt02 commented on App/Components/Chat/CompChatView.razor
> +    private User? OtherUser
noticing an issue here; this property doesn't adequately account for changes to the other user in the dm when switching DM views (i.e., the chat id parameter is set) the header remains the same, but the member list changes.

2024-04-09 03:24 UTC, bhunt02 commented on App/Components/Chat/CompChatView.razor
> +    private List<MessageEntry> Messages { get; set; } = [];
Messages, EphemeralMessages & MessageIdToIndex are not cleared out when the chat is changed, so the same messages are taken to each different chat display :(

2024-04-09 03:24 UTC, bhunt02 commented on App/Classes/Services/UserServices/UserInteractionService.cs
> +    private SemaphoreSlim SubscribersLock { get; } = new(1, 1);
the semaphore here doesn't appear to work in preventing errors when the subscriber list is modified - can see that an error is thrown when unfriending someone while in the dm view for them

2024-04-09 03:58 UTC, Bawnorton commented on App/Components/Chat/CompChatView.razor
> +        if (string.IsNullOrWhiteSpace(messageText) && FileData.Count == 0) return;
Is this no longer needed per #143? Should I include it anyway?

2024-04-09 04:10 UTC, bhunt02 commented on App/Components/Chat/CompChatView.razor
> +        if (string.IsNullOrWhiteSpace(messageText) && FileData.Count == 0) return;
include it anyway for now, i am exploring into making a rudimentary basic 'system message' sort of interaction.

2024-04-09 04:12 UTC, Bawnorton commented on App/Components/Chat/CompChatView.razor
> +        if (string.IsNullOrWhiteSpace(messageText) && FileData.Count == 0) return;
alr, can probably use that for pinning too provided it's plug-and-play-able

2024-04-10 07:07 UTC, bhunt02 approved these changes

2024-04-10 07:08 UTC, merged